name: Continuous Integration
env:
  COMPOSER: composer-with-dependencies.json
on:
  push:
  pull_request:
  schedule:
    # Run every day at 7:14PM
    - cron: "14 19 * * *"
jobs:
  build:
    name: HHVM ${{matrix.hhvm}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ubuntu]
        hhvm:
          - "4.128"
          - "4.153"
          - "4.168"
    runs-on: ${{matrix.os}}-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Create branch for version alias
        run: git checkout -b CI_current_pull_request
      - uses: hhvm/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
          skip_lint: true
          skip_tests: true
